repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npm run lint
        language: system
        pass_filenames: false
        files: '\.(js|ts|vue)$'
      - id: typecheck
        name: TypeScript
        entry: npm run typecheck
        language: system
        pass_filenames: false
        files: '\.(ts|vue)$'
